const VALIDATION_CONCEPT_BY_CODE = {
  "allegiance_ability.group_limit_exceeded": "AllegianceAbilityGroupRosterLimitValidator",
  "allegiance_ability.group_limit_not_reached": "AllegianceAbilityGroupRosterLimitValidator",
  "allegiance_ability.mandatory_not_selected": "AllegianceAbilityValidator",
  "allegiance_ability.missing_wargear_item": "AllegianceAbilityValidator",
  "allegiance_ability.multiple_selected": "AllegianceAbilityValidator",
  "allegiance_ability.not_allowed": "AllegianceAbilityValidator",
  "allegiance_ability.not_selected": "AllegianceAbilityValidator",
  "allegiance_ability.required_detachment_missing": "AllegianceAbilityValidator",
  "allied_faction.datasheet_not_allowed": "AlliedFactionDatasheetValidator",
  "allied_faction.not_available": "AlliedFactionValidator",
  "allied_keyword_count.invalid_mutually_exclusive_keywords": "InvalidMutuallyExclusiveKeywords",
  "allied_keyword_count.limit_exceeded": "AlliedKeywordCountValidator",
  "allied_keyword_restricting_keyword.outnumbered_keywords": "KeywordAllyRestrictingKeywordValidator",
  "allied_points.limit_exceeded": "AlliedPointsValidator",
  "allied_unit.required_allegiance_ability_missing": "AlliedUnitsRequiredAllegianceValidator",
  "allied_unit.required_detachment_not_selected": "AlliedFactionDetachmentValidator",
  "allied_units.required_warlord_missing": "AlliedUnitsRequiredWarlordValidator",
  "attached_unit.duplicate_membership": "RosterAttachedUnitValidator",
  "attached_unit.incomplete": "RosterAttachedUnitValidator",
  "attached_unit.missing_requirements": "RosterAttachedUnitValidator",
  "attached_unit.must_be_attached": "UnitMustBeAttached",
  "detachment.datasheet_not_allowed": "DetachmentExcludedDatasheetValidator",
  "detachment.datasheets_missing": "DetachmentRequiredDatasheetValidator",
  "detachment.linked_datasheet_count_mismatch": "DetachmentRequiredDatasheetValidator",
  "detachment.linked_datasheet_not_allowed": "DetachmentRequiredDatasheetValidator",
  "enhancement.allied_unit_not_allowed": "EnhancementValidator",
  "enhancement.attached_requirement_missing": "EnhancementValidator",
  "enhancement.attached_unit_too_many_enhancements": "EnhancementValidator",
  "enhancement.combat_patrol_multiple_selected": "EnhancementValidator",
  "enhancement.combat_patrol_not_allowed": "EnhancementValidator",
  "enhancement.combat_patrol_required": "EnhancementValidator",
  "enhancement.epic_hero_not_allowed": "EnhancementValidator",
  "enhancement.model_count_zero": "EnhancementValidator",
  "enhancement.model_does_not_have_required_keywords": "EnhancementValidator",
  "enhancement.model_does_not_have_required_wargear": "EnhancementValidator",
  "enhancement.model_excluded": "EnhancementValidator",
  "enhancement.model_must_not_have_excluded_keywords": "EnhancementValidator",
  "enhancement.models_have_same_enhancements": "EnhancementValidator",
  "enhancement.required_detachment_missing": "EnhancementValidator",
  "enhancement.roster_has_too_many_enhancements": "EnhancementValidator",
  "enhancement.target_type_invalid": "EnhancementValidator",
  "enhancement.unit_does_not_have_required_keywords": "EnhancementValidator",
  "enhancement.unit_has_too_many_enhancements": "EnhancementValidator",
  "keyword_restriction_group.limit_exceeded": "KeywordRestrictionGroupValidator",
  "keyword_restriction_group.limit_zero": "KeywordRestrictionGroupValidator",
  "keyword_restriction_group.minimum_not_met": "KeywordRestrictionGroupValidator",
  "mandatory_warlord.detachment_not_selected": "MandatoryWarlordValidator",
  "mandatory_warlord.not_present_in_roster": "MandatoryWarlordValidator",
  "mandatory_warlord.not_selected": "MandatoryWarlordValidator",
  "mandatory_warlord.supreme_commander_not_selected": "SupremeCommanderNotSelected",
  "roster.combat_patrol_datasheet": "RosterUnitValidator",
  "roster.detachment_not_allowed": "RosterDetachmentValidator",
  "roster.detachment_not_selected": "RosterDetachmentValidator",
  "roster.detachment_points_limit_exceeded": "DetachmentPointsLimitValidator",
  "roster.detachment_unique_keyword_error": "RosterDetachmentValidator",
  "roster.empty": "BuilderRosterWarning",
  "roster.faction_datasheet_not_allowed": "FactionKeywordExcludedDatasheetValidator",
  "roster.points_limit_exceeded": "RosterPointsValidator",
  "roster.successor_chapter_epic_hero_in_roster": "RosterUnitLimitValidator",
  "roster.unit_limit_exceeded": "RosterUnitLimitValidator",
  "roster.unit_not_native": "RosterUnitValidator",
  "unit.max_model_count_too_many_models": "MaxModelCountValidator",
  "unit_composition.invalid_unit_composition": "UnitCompositionValidator",
  "unit_composition.unavailable": "UnitCompositionValidator",
  "wargear_loadout.invalid_miniature_wargear_loadout": "InvalidWargearLoadout",
  "wargear_loadout.invalid_model_wargear": "WargearLoadoutValidator",
  "wargear_loadout.invalid_unit_wargear": "WargearLoadoutValidator",
  "wargear_loadout.invalid_unit_wargear_loadout": "InvalidWargearLoadout",
  "wargear_loadout.invalid_wargear_requirement": "InvalidWargearRequirement",
  "wargear_loadout.zero_count_model_wargear": "WargearLoadoutValidator",
  "warlord.invalid_due_to_enhancement": "InvalidWarlordDueToEnhancements",
  "warlord.invalid_generic": "WarlordValidator",
  "warlord.multiple_selected": "WarlordValidator",
  "warlord.not_selected": "WarlordValidator",
};

const OFFICIAL_VALIDATION_KEY_TO_CODE = {
  "allegiance_ability_group_limit_exceeded": "allegiance_ability.group_limit_exceeded",
  "allegiance_ability_group_limit_not_reached": "allegiance_ability.group_limit_not_reached",
  "allegiance_ability_missing_wargear_item": "allegiance_ability.missing_wargear_item",
  "allegiance_ability_multiple_selected": "allegiance_ability.multiple_selected",
  "allegiance_ability_not_selected": "allegiance_ability.not_selected",
  "allied_keyword_count_invalid_mutually_exclusive_keywords": "allied_keyword_count.invalid_mutually_exclusive_keywords",
  "allied_keyword_count_limit_exceeded": "allied_keyword_count.limit_exceeded",
  "allied_keyword_count_warlord_keyword_count_limit_exceeded": "allied_keyword_count.limit_exceeded",
  "allied_keyword_restricting_keyword_outnumbered_keywords": "allied_keyword_restricting_keyword.outnumbered_keywords",
  "allied_keyword_restricting_keyword_outnumbered_keywords_no_faction": "allied_keyword_restricting_keyword.outnumbered_keywords",
  "allied_points_limit_exceeded": "allied_points.limit_exceeded",
  "allied_unit_required_allegiance_ability_missing": "allied_unit.required_allegiance_ability_missing",
  "allied_unit_required_detachment_not_selected": "allied_unit.required_detachment_not_selected",
  "allied_units_required_warlord_missing": "allied_units.required_warlord_missing",
  "attach_unit_required": "attached_unit.must_be_attached",
  "attached_unit_detachment_no_matching_keyword": "attached_unit.missing_requirements",
  "attached_unit_leader_missing_requirements": "attached_unit.missing_requirements",
  "attached_unit_no_matching_keyword": "attached_unit.missing_requirements",
  "attached_unit_support_missing_requirements": "attached_unit.missing_requirements",
  "conditional_keyword_missing_keyword_to_be_warlord": "warlord.invalid_generic",
  "detachment_datasheet_not_allowed": "detachment.datasheet_not_allowed",
  "detachment_datasheets_missing": "detachment.datasheets_missing",
  "detachment_not_selected": "roster.detachment_not_selected",
  "detachment_points_limit_exceeded": "roster.detachment_points_limit_exceeded",
  "detachment_unique_keyword_error": "roster.detachment_unique_keyword_error",
  "enhancement_attached_unit_too_many_enhancements": "enhancement.attached_unit_too_many_enhancements",
  "enhancement_model_does_not_have_required_keywords": "enhancement.model_does_not_have_required_keywords",
  "enhancement_model_must_not_have_excluded_keywords": "enhancement.model_must_not_have_excluded_keywords",
  "enhancement_models_have_same_enhancements": "enhancement.models_have_same_enhancements",
  "enhancement_roster_has_too_many_enhancements": "enhancement.roster_has_too_many_enhancements",
  "enhancementModelDoesNotHaveRequiredWargear": "enhancement.model_does_not_have_required_wargear",
  "invalid_warlord_due_to_enhancement": "warlord.invalid_due_to_enhancement",
  "invalid_warlord_generic": "warlord.invalid_generic",
  "keyword_restriction_group_error": "keyword_restriction_group.limit_exceeded",
  "keyword_restriction_group_error_excluded_faction": "keyword_restriction_group.limit_exceeded",
  "keyword_restriction_group_error_excluded_faction_limit_zero": "keyword_restriction_group.limit_zero",
  "keyword_restriction_group_error_limit_zero": "keyword_restriction_group.limit_zero",
  "keyword_restriction_group_error_minimum_not_met": "keyword_restriction_group.minimum_not_met",
  "keyword_restriction_group_error_roster_warlord": "keyword_restriction_group.limit_exceeded",
  "keyword_restriction_group_error_roster_warlord_limit_zero": "keyword_restriction_group.limit_zero",
  "mandatory_warlord_not_present_in_roster": "mandatory_warlord.not_present_in_roster",
  "mandatory_warlord_not_selected_multiple": "mandatory_warlord.not_selected",
  "mandatory_warlord_not_selected_single": "mandatory_warlord.not_selected",
  "mandatory_warlord_supreme_command_not_selected": "mandatory_warlord.supreme_commander_not_selected",
  "max_model_count_too_many_models": "unit.max_model_count_too_many_models",
  "roster_points_points_limit_exceeded": "roster.points_limit_exceeded",
  "roster_unit_limit_datasheet_limit_exceeded": "roster.unit_limit_exceeded",
  "roster_unit_limit_epic_hero_exceeded": "roster.unit_limit_exceeded",
  "successor_chapter_epic_hero_in_roster": "roster.successor_chapter_epic_hero_in_roster",
  "unit_composition_invalid_unit_composition": "unit_composition.invalid_unit_composition",
  "wargear_loadout_invalid_miniature_wargear_loadout": "wargear_loadout.invalid_miniature_wargear_loadout",
  "wargear_loadout_invalid_miniature_wargear_loadout_single_model": "wargear_loadout.invalid_miniature_wargear_loadout",
  "wargear_loadout_invalid_unit_wargear_loadout": "wargear_loadout.invalid_unit_wargear_loadout",
  "wargear_loadout_invalid_wargear_requirement": "wargear_loadout.invalid_wargear_requirement",
  "warlord_validator_multiple_warlords_selected": "warlord.multiple_selected",
  "warlord_validator_warlord_not_selected": "warlord.not_selected",
};

const OFFICIAL_VALIDATION_CONCEPTS = new Set([
  ...Object.values(VALIDATION_CONCEPT_BY_CODE),
  "LoadoutKey",
]);

function validationConceptForCode(code) {
  return VALIDATION_CONCEPT_BY_CODE[code] || "";
}

function validationConceptKnown(concept) {
  return OFFICIAL_VALIDATION_CONCEPTS.has(concept);
}

export {
  OFFICIAL_VALIDATION_CONCEPTS,
  OFFICIAL_VALIDATION_KEY_TO_CODE,
  VALIDATION_CONCEPT_BY_CODE,
  validationConceptForCode,
  validationConceptKnown,
};
