const VALIDATION_CONCEPT_BY_CODE = {
  "allegiance_ability.group_limit_exceeded": "AllegianceAbilityGroupRosterLimitValidator",
  "allegiance_ability.group_limit_not_reached": "AllegianceAbilityGroupRosterLimitValidator",
  "allegiance_ability.mandatory_not_selected": "AllegianceAbilityValidator",
  "allegiance_ability.missing_wargear_item": "AllegianceAbilityValidator",
  "allegiance_ability.multiple_selected": "AllegianceAbilityValidator",
  "allegiance_ability.not_allowed": "AllegianceAbilityValidator",
  "allegiance_ability.not_selected": "AllegianceAbilityValidator",
  "allegiance_ability.required_detachment_missing": "AllegianceAbilityValidator",
  "allied_faction.datasheet_not_allowed": "AlliedFactionDatasheetValidator",
  "allied_faction.not_available": "AlliedFactionValidator",
  "allied_keyword_count.invalid_mutually_exclusive_keywords": "InvalidMutuallyExclusiveKeywords",
  "allied_keyword_count.limit_exceeded": "AlliedKeywordCountValidator",
  "allied_keyword_restricting_keyword.outnumbered_keywords": "KeywordAllyRestrictingKeywordValidator",
  "allied_points.limit_exceeded": "AlliedPointsValidator",
  "allied_unit.required_allegiance_ability_missing": "AlliedUnitsRequiredAllegianceValidator",
  "allied_unit.required_detachment_not_selected": "AlliedFactionDetachmentValidator",
  "allied_units.required_warlord_missing": "AlliedUnitsRequiredWarlordValidator",
  "attached_unit.duplicate_membership": "RosterAttachedUnitValidator",
  "attached_unit.incomplete": "RosterAttachedUnitValidator",
  "attached_unit.missing_requirements": "RosterAttachedUnitValidator",
  "attached_unit.must_be_attached": "UnitMustBeAttached",
  "detachment.datasheet_not_allowed": "DetachmentExcludedDatasheetValidator",
  "detachment.datasheets_missing": "DetachmentRequiredDatasheetValidator",
  "detachment.linked_datasheet_count_mismatch": "DetachmentRequiredDatasheetValidator",
  "detachment.linked_datasheet_not_allowed": "DetachmentRequiredDatasheetValidator",
  "enhancement.allied_unit_not_allowed": "EnhancementValidator",
  "enhancement.attached_requirement_missing": "EnhancementValidator",
  "enhancement.attached_unit_too_many_enhancements": "EnhancementValidator",
  "enhancement.combat_patrol_multiple_selected": "EnhancementValidator",
  "enhancement.combat_patrol_not_allowed": "EnhancementValidator",
  "enhancement.combat_patrol_required": "EnhancementValidator",
  "enhancement.epic_hero_not_allowed": "EnhancementValidator",
  "enhancement.model_count_zero": "EnhancementValidator",
  "enhancement.model_does_not_have_required_keywords": "EnhancementValidator",
  "enhancement.model_does_not_have_required_wargear": "EnhancementValidator",
  "enhancement.model_excluded": "EnhancementValidator",
  "enhancement.model_must_not_have_excluded_keywords": "EnhancementValidator",
  "enhancement.models_have_same_enhancements": "EnhancementValidator",
  "enhancement.required_detachment_missing": "EnhancementValidator",
  "enhancement.roster_has_too_many_enhancements": "EnhancementValidator",
  "enhancement.target_type_invalid": "EnhancementValidator",
  "enhancement.unit_does_not_have_required_keywords": "EnhancementValidator",
  "enhancement.unit_has_too_many_enhancements": "EnhancementValidator",
  "keyword_restriction_group.limit_exceeded": "KeywordRestrictionGroupValidator",
  "keyword_restriction_group.limit_zero": "KeywordRestrictionGroupValidator",
  "keyword_restriction_group.minimum_not_met": "KeywordRestrictionGroupValidator",
  "mandatory_warlord.detachment_not_selected": "MandatoryWarlordValidator",
  "mandatory_warlord.not_present_in_roster": "MandatoryWarlordValidator",
  "mandatory_warlord.not_selected": "MandatoryWarlordValidator",
  "mandatory_warlord.supreme_commander_not_selected": "SupremeCommanderNotSelected",
  "roster.combat_patrol_datasheet": "RosterUnitValidator",
  "roster.detachment_not_allowed": "RosterDetachmentValidator",
  "roster.detachment_not_selected": "RosterDetachmentValidator",
  "roster.detachment_points_limit_exceeded": "DetachmentPointsLimitValidator",
  "roster.detachment_unique_keyword_error": "RosterDetachmentValidator",
  "roster.empty": "BuilderRosterWarning",
  "roster.faction_datasheet_not_allowed": "FactionKeywordExcludedDatasheetValidator",
  "roster.points_limit_exceeded": "RosterPointsValidator",
  "roster.successor_chapter_epic_hero_in_roster": "RosterUnitLimitValidator",
  "roster.unit_limit_exceeded": "RosterUnitLimitValidator",
  "roster.unit_not_native": "RosterUnitValidator",
  "unit.max_model_count_too_many_models": "MaxModelCountValidator",
  "unit_composition.invalid_unit_composition": "UnitCompositionValidator",
  "unit_composition.unavailable": "UnitCompositionValidator",
  "wargear_loadout.invalid_miniature_wargear_loadout": "InvalidWargearLoadout",
  "wargear_loadout.invalid_model_wargear": "WargearLoadoutValidator",
  "wargear_loadout.invalid_unit_wargear": "WargearLoadoutValidator",
  "wargear_loadout.invalid_unit_wargear_loadout": "InvalidWargearLoadout",
  "wargear_loadout.invalid_wargear_requirement": "InvalidWargearRequirement",
  "wargear_loadout.zero_count_model_wargear": "WargearLoadoutValidator",
  "warlord.invalid_due_to_enhancement": "InvalidWarlordDueToEnhancements",
  "warlord.invalid_generic": "WarlordValidator",
  "warlord.multiple_selected": "WarlordValidator",
  "warlord.not_selected": "WarlordValidator",
};

function validationConceptForCode(code) {
  return VALIDATION_CONCEPT_BY_CODE[code] || "";
}

export {
  VALIDATION_CONCEPT_BY_CODE,
  validationConceptForCode,
};
